export const serwis = {
  url: {
    site: "naprawaprzemysl.pl",
    facebook: "https://www.facebook.com/100063811592941",
    fb_app_id: "1465845357931091",
    // google: "https://g.co/kgs/XdcEw7o",
    // google: "https://www.google.com/maps/place/Naprawa+pralek+i+sprz%C4%99tu+RTV+-+naprawa+ekspres%C3%B3w+do+kawy,+naprawa+telewizor%C3%B3w,+naprawa+zmywarki,+serwis+agd,/@49.7827725,22.776029,17z/data=!3m1!4b1!4m6!3m5!1s0x473b7f241be960ad:0xfc3cd55238f8f8a6!8m2!3d49.7827725!4d22.776029!16s%2Fg%2F1w0j2zhh?entry=ttu&g_ep=EgoyMDI1MDUxNS4xIKXMDSoASAFQAw%3D%3D",
    google: "https://maps.google.com/?cid=18175636745280354470", // raczej nie przydatny
    addTestimonial: "https://g.page/r/Cab4-DhS1Tz8EAE/review",
    GMF: "https://g.page/r/Cab4-DhS1Tz8EAE",
  },
//  name: "Naprawa pralek i sprzętu RTV - naprawa ekspresów do kawy, naprawa telewizorów, naprawa zmywarki, serwis agd,",
  // subName: "Serwis RTV i AGD",
  // name: "Piotr Matusiewicz Sklep-Komis Serwis RTV i AGD",
  person: "Piotr Matusiewicz",
 name: "Serwis RTV i AGD w Przemyślu",
//  name: "Naprawa pralek i sprzętu RTV",
  subName: "Naprawa pralek i sprzętu RTV - naprawa ekspresów do kawy, naprawa telewizorów, naprawa zmywarki, serwis agd,",
  shortName: "Serwis RTV i AGD",
  email: "piotrek_serwis@wp.pl",
  phone: {
    number: "+48790258612",
    international: "+48 790 258 612",
    formatted: "790 258 612",
    short: "790258612"
  },
  adres: "Generała Józefa Sowińskiego 2, 37-700 Przemyśl",
  area: [
    "Przemyśl",
    "Bolestraszyce",
    "Duńkowiczki",
    "Krówniki",
    "Nehrybka",
    "Orzechowce",
    "Ostrów",
    "Pikulice",
    "Prałkowce",
    "Wyszatyce",
    "Żurawica"
  ],
  reviews: [
    {
      "reveiwFor": "telewizor",
      "author_name": "egon920",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocLeFaeToPvK4IxM7u-evnpZcT-b841ZOKvBOmgumUVbm_O0ug=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Super fachowiec. Mało mówi, za to dużo robi... dobrego :-) W moim 46 calowym Samsungu padło podświetlenie i dzięki temu Panu TV odżył, za stosunkowo nie duże pieniądze, w porównaniu z ceną nowego odpowiednika TV.",
      "time": 1739309092,
    },
    {
      "reveiwFor": "ekspres",
      "author_name": "Marta M",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocKRA0X6LgORfbVanU44l8XjOW-IJJUIFHWTHd7RQiu8Db4dfQ=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Z czystym sumieniem polecam serwis za profesjonalne czyszczenie mojego ekspresu do kawy! Usługa została wykonana szybko i z najwyższą starannością. Ekspres działa teraz jak nowy, a smak kawy zyskał zupełnie nową jakość. Fachowa obsługa, miły kontakt i konkurencyjne ceny sprawiają, że na pewno wrócę przy kolejnych potrzebach. Serdecznie dziękuję za tak świetną pracę!",
      "time": 1726153581,
    },
    {
      "reveiwFor": "pralka",
      "author_name": "Bartosz Zawalski",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocL9kBYJPRN2gJJDEP6WZKkuqM-Wn_a1YmdA0rPIoR3W_Y2beA=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Naprawa pralki, szybka i trafna diagnoza. Realizacja naprawy, praktycznie z dnia na dzień nie licząc czasu oczekiwania na cześć zmienną. Polecam serdecznie Pana zna się na swoim fachu. SZYBKI kontakt i szacun za rzetelność.",
      "time": 1727166486,
    },
    {
      "reveiwFor": "zmywarka",
      "author_name": "Magda Ryzner",
      "profile_photo_url": "https://lh3.googleusercontent.com/a-/ALV-UjVr2VP_YAmNfKDbP-mV52eBkBpcgI6yWQ1SR4vAgK_QaPdQMKU_=s128-c0x00000000-cc-rp-mo-ba3",
      "rating": 5,
      "text": "Już kilkakrotnie Pan Piotr naprawiał nam niedziałające sprzęty AGD. Wszystkie działają do tej pory i mają się dobrze. Bardzo dziękuję Panu Piotrowi za szybką i profesjonalną usługę. Szczerze polecam.",
      "time": 1727075329,
    },
    {
      "reveiwFor": "suszarka",
      "author_name": "m p",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocKMSawUWjzTWhs4s32zarbOVNuEUNu7aZJeNd-kuTXdhkVt=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Super profesjonalizm, przystępne ceny i szybkie terminy - zdecydowanie polecam",
      "time": 1720075559,
    },
    {
      "author_name": "EL-METR INSTALACJE Zbigniew Banasiewicz",
      "profile_photo_url": "https://lh3.googleusercontent.com/a-/ALV-UjUhgXMZOtY6kHJX4P7H85Jj7h41sBXlaf3kQFJnt2Zjwxw57KmG=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Pan z ogromną wiedzą i doświadczeniem. Już kilka napraw za nami , wszystko naprawione i działa. Polecam Pana Piotra. Najlepszy elektronik w mieście. Pozdrawiam",
      "time": 1684091120,
    },
  ],
  ratingsTotal: 66,
  rating: 4.6,
  types: [
    "point_of_interest",
    "establishment"
  ],
};
